version: 1

# List of env variables used during compilation.
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

# Flags for the compiler.
flags:
  - -trimpath
  - -tags=netgo

# The OS to compile for. `GOOS` env variable will be set to these values.
goos:
  - linux
  - darwin
  - windows

# The architecture to compile for. `GOARCH` env variable will be set to these values.
goarch:
  - amd64
  - arm64

# Binary output name.
# {{ .Os }} will be replaced by goos field in the config file.
# {{ .Arch }} will be replaced by goarch field in the config file.
binary: godeeplapi-{{ .Os }}-{{ .Arch }}

# (Optional) ldflags generated dynamically in the workflow.
# These use environment variables that are automatically set by the SLSA builder
ldflags:
  - "-s -w"
  - "-X main.Version={{ .Env.VERSION }}"
  - "-X main.Commit={{ .Env.COMMIT }}"