name: Go Build and Release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]
    
jobs: 
  build:
    name: Build Go Binary
    runs-on: ubuntu-latest
    # For push and pull requests, just build (don't release)
    if: github.event_name != 'release'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  release:
    name: Release Go Binary
    # Only run this job when a release is created
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.24.1.linux-amd64.tar.gz"
        project_path: "./"
        binary_name: "godeeplapi"
        extra_files: LICENSE README.md
        # This will use the actual tag from the release event (like v0.1.0)
        release_tag: ${{ github.ref_name }}
