name: Debug Directory
on: [workflow_dispatch]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -la
          echo "Looking for .slsa-goreleaser.yml:"
          find . -name ".slsa-goreleaser.yml" -o -name "slsa-goreleaser.yml"
          echo "Content of file (if exists):"
          if [ -f ".slsa-goreleaser.yml" ]; then
            cat .slsa-goreleaser.yml
          elif [ -f "slsa-goreleaser.yml" ]; then
            cat slsa-goreleaser.yml
          else
            echo "No configuration file found"
          fi
